Switching back to bash because Process substituation is not supported in sh

diff --git a/sysconfig-snapshot b/sysconfig-snapshot
--- a/sysconfig-snapshot
+++ b/sysconfig-snapshot
@@ -1,4 +1,4 @@
-#!/bin/sh - 
+#!/bin/bash  
 #
 # Purpose : Capture the state of the system configuration for later
 # troubleshooting in the event of system problems. The given data will be stored
@@ -20,19 +20,19 @@ VERBOSE=false
 CURRENTHOST=$(hostname) 
 DATETIME=$(date +%m%d%y_%H%M%S) 
 TARGETDIR=/var/log/sysconfig-snapshot
-SYSCONFIGFILE=$TARGETDIR/snapshot.$CURRENTHOST.$DATETIME
+SYSCONFIGFILE=$TARGETDIR/snapshot.$CURRENTHOST.$DATETIME.gz
 
 #Functions definition 
 
 error() 
 {
-   echo "$@" 1>&2 
+   echo -e "$@" 1>&2 
    usage_and_exit 1 
 }
 
 usage() 
 {  
-   echo "Usage: $PROGRAM [--output file] [--verbose] [--help] [--version]"
+   echo -e "Usage: $PROGRAM [--output file] [--verbose] [--help] [--version]"
          
 }
 
@@ -44,7 +44,7 @@ usage_and_exit()
 
 version() 
 { 
-   echo "$PROGRAM version $VERSION" 
+   echo -e "$PROGRAM version $VERSION" 
 }
 
 get_os() 
@@ -119,7 +119,7 @@ get_partition_table()
 get_fs_stats()
 {
    df -k 
-   echo "\n"
+   echo -e "\n"
    mount
 }
 
@@ -142,39 +142,39 @@ get_ps_list()
 
 generate_report()
 {
-   echo "\n\n $PROGRAM ($VERSION) - $(date) \n\n"
-   echo "\n###############################################################\n"
-   echo "\tGENERAL:"
-   echo "\n###############################################################\n"
-   echo "#Hostname:\t\t$CURRENTHOST"
-   echo "#Time Zone:\t\t$(get_timezone)"
-   echo "#Machine Architecture:\t$(get_arch)"
-   echo "#Operating System:\t$(get_os)"
-   echo "#Distribution:\t\t$(get_distro)"
-   echo "\n###############################################################\n"
-   echo "\tHARDWARE:"
-   echo "\n###############################################################\n"
-   echo "#CPU:\n\n$(get_cpu_info)\n" 
-   echo "#Physical Memory:\n\n$(get_real_mem)\n" 
-   echo "#Swap Memory:\n\n$(get_swap)\n" 
-   echo "#DMI table:\n\n$(get_dmi_table)\n" 
-   echo "#PCI devices list:\n\n$(get_pci_list)\n" 
-   echo "#Device directory list - /dev:\n\n$(get_long_dev_list)\n" 
-   echo "\n###############################################################\n"
-   echo "\tFILE SYSTEM:"
-   echo "\n###############################################################\n"
-   echo "#Block devices list:\n\n$(get_block_dev_list)\n" 
-   echo "#Partition table:\n$(get_partition_table)\n" 
-   echo "#File system stats:\n\n$(get_fs_stats)\n" 
-   echo "\n###############################################################\n"
-   echo "\tNETWORKING:"
-   echo "\n###############################################################\n"
-   echo "#Interfaces list:\n\n$(get_ifaces_list)\n" 
-   echo "#IP routing table:\n\n$(get_route_table)\n" 
-   echo "\n###############################################################\n"
-   echo "\tPROCESSES:"
-   echo "\n###############################################################\n"
-   echo "#Process list:\n\n$(get_ps_list)\n" 
+   echo -e "\n\n $PROGRAM ($VERSION) - $(date) \n\n"
+   echo -e "\n###############################################################\n"
+   echo -e "\tGENERAL:"
+   echo -e "\n###############################################################\n"
+   echo -e "#Hostname:\t\t$CURRENTHOST"
+   echo -e "#Time Zone:\t\t$(get_timezone)"
+   echo -e "#Machine Architecture:\t$(get_arch)"
+   echo -e "#Operating System:\t$(get_os)"
+   echo -e "#Distribution:\t\t$(get_distro)"
+   echo -e "\n###############################################################\n"
+   echo -e "\tHARDWARE:"
+   echo -e "\n###############################################################\n"
+   echo -e "#CPU:\n\n$(get_cpu_info)\n" 
+   echo -e "#Physical Memory:\n\n$(get_real_mem)\n" 
+   echo -e "#Swap Memory:\n\n$(get_swap)\n" 
+   echo -e "#DMI table:\n\n$(get_dmi_table)\n" 
+   echo -e "#PCI devices list:\n\n$(get_pci_list)\n" 
+   echo -e "#Device directory list - /dev:\n\n$(get_long_dev_list)\n" 
+   echo -e "\n###############################################################\n"
+   echo -e "\tFILE SYSTEM:"
+   echo -e "\n###############################################################\n"
+   echo -e "#Block devices list:\n\n$(get_block_dev_list)\n" 
+   echo -e "#Partition table:\n$(get_partition_table)\n" 
+   echo -e "#File system stats:\n\n$(get_fs_stats)\n" 
+   echo -e "\n###############################################################\n"
+   echo -e "\tNETWORKING:"
+   echo -e "\n###############################################################\n"
+   echo -e "#Interfaces list:\n\n$(get_ifaces_list)\n" 
+   echo -e "#IP routing table:\n\n$(get_route_table)\n" 
+   echo -e "\n###############################################################\n"
+   echo -e "\tPROCESSES:"
+   echo -e "\n###############################################################\n"
+   echo -e "#Process list:\n\n$(get_ps_list)\n" 
 }
 
 #Command-line argument parser
@@ -210,29 +210,29 @@ done
 
 if [ "$(uname -s)" != 'Linux' ]
 then 
-   echo "\n Error : This shell script is written exclusively for Linux OS.\n"
+   echo -e "\n Error : This shell script is written exclusively for Linux OS.\n"
    exit 1
 fi
 
-if [ ! -d $TARGETDIR ]
+if [ ! -d "$TARGETDIR" ]
 then
    mkdir -p $TARGETDIR > /dev/null 2>&1
    if [  $? != 0 ]
    then 
-      echo "\n Error : Permission denied, cannot create $TARGETDIR directory.\n"
+      echo -e "\n Error : Permission denied, cannot create $TARGETDIR directory.\n"
       exit 2
    fi
 fi
    
 if [ $VERBOSE = true ] 
 then
-   generate_report | tee -a $SYSCONFIGFILE  
+   generate_report | tee >(gzip > $SYSCONFIGFILE)
 else
-   generate_report > $SYSCONFIGFILE 2> /dev/null 
+   generate_report | gzip > $SYSCONFIGFILE 2> /dev/null 
 fi
 
 if [ -e "$SYSCONFIGFILE" ]
 then
-   echo "\nThis report is successfully saved in : $SYSCONFIGFILE\n"
+   echo -e "\nThis report is successfully saved in : $SYSCONFIGFILE\n"
    exit 0
 fi
